### ISSUE TITLE
Problems with the ships bin PC/Valkyrie Patch

### ISSUE THREAD

**Issue by JoshuaSpeckels** [Ravernstal/gof2edit#1]
When trying to use ships.bin with this Editor while using the PC Version with the Valkyrie Patch, things start to go wrong. If you edit the skanar, the ship transforms ingame into either a nemesis or a ksuuk, since all three ships are part of the valkyrie patch I suspect that the problems stems from there.

**Comment by Ravernstal** [comment]
I think the problem with the Valkyrie Patch is that it doesn't use the ship IDs of the ships it replaces, so instead it creates duplicate IDs in `ships.bin`. Although I'm not entirely sure how the patch works, I don't think this is an issue with `gof2edit`.
