### ISSUE TITLE
Handle ticker.bin

### ISSUE THREAD

**Issue by Trimatix** [Ravernstal/gof2edit#4]
File structure in gof2-bin-info: https://github.com/Ravernstal/gof2-bin-info/blob/master/ticker.md

**Comment by Trimatix** [comment]
I'd like to take this issue :)

**Comment by Ravernstal** [comment]
What's tickets.bin?

**Comment by Trimatix** [comment]
Typo, apologies!

**Comment by Ravernstal** [comment]
Oh. Sorry, gof2edit already handles that file. See [here](https://github.com/Ravernstal/gof2edit/blob/master/src/data/news_item.rs).
